(define (true . ignore) #t)
(define (false . ignore) #f)

(format #t "~% (and #f #t) ~a" (and (false 1) (true 3)))
(format #t "~% (and #t #f) ~a" (and (true 3) (false 1)))
(format #t "~% (and #t #t) ~a" (and (true 3) (true 3)))
(format #t "~% (or #t #t) ~a" (or (true 3) (true 3)))
(format #t "~% (or #f #t) ~a" (or (false 1) (true 3)))
(format #t "~% (or #t #f) ~a" (or (true 3) (false 1)))
(format #t "~% (or #f #f) ~a" (or (false 1) (false 1)))
(format #t "~% (or #f #f #f) ~a" (or (false 1) (false 1) (false 1)))
(format #t "~% (and #t (not (or #f #f #t))) ~a" (and (true 5) (not (or (false 1) (false 1) (true 3)))))
(format #t "~% (and #t (not (or #f #f #f))) ~a" (and (true 3) (not (or (false 1) (false 1) (false 1)))))
(newline)