(let ()
 (define (even n) (if (= n 0) #t (odd  (- n 1))))
 (define (odd  n) (if (= n 0) #f (even (- n 1))))
 (display "(even 7) is ")
 (display (even 7))
 (newline)
 (display "(odd 17) is ")
 (display (odd 17)))
